### ISSUE TITLE
Question: Immutable trees and tree modification

### ISSUE THREAD

**Issue by skyne98** [domenicquirl/cstree#24] opened 2021-04-10 17:00 UTC
Hey there! 

I have been recently rewriting my toy compiler for my toy language and I came across your `rowan`-inspired library, really liked the concepts, even though I am still very new with all the "green" and "red" trees 😃.

Would it be possible or hard to write a couple of small examples regarding such topics like:
1. How does one partially modify a tree of syntax nodes (or create a partially-reused copy with those modifications)? Let's say, when transforming it from AST to HIR (de-sugaring) or simply changing one identifier in the tree?
2. How does one reuse the trees during incremental recompilation? Is it related to using a `NodeCache`?

In-advance, thanks for your time and answers, always hoping to find out something for myself!

**Comment by domenicquirl** [comment] 2021-04-10 18:49
Hi, and thanks for you interest!
If you've looked at our docs and `rowan`, I assume you have also already looked through https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/syntax.md ? I tried to substantially expand the docs when I made this fork, but that `rust-analyzer` document is still the most extensive writeup I know of. If you're looking for a bit more on the topic, there is also https://ericlippert.com/2012/06/08/red-green-trees/ and https://github.com/KirillOsenkov/Bliki/wiki/Roslyn-Immutable-Trees (sadly, I don't have a corresponding writeup that precisely matches `cstree`'s implementation).

Regarding your questions: mutable trees don't easily fit the rest of the implementation, which focuses on deduplication and maintaining some level of efficiency (storing node/token info like their `SyntaxKind` together with the children of a node/the text of a token; being able to pass elements around as pointers or references; not hashing or cloning things all the time). 
In particular, if you swap one node with another node that is different (let's lay it is longer), then the offset of all nodes after it have to update (in this case, they'd have to move to a bigger offset in the input). The problem is that the change (swapping the node) is local, but affects the entire tree. So, for example, if you go up 5 parents and right one sibling, all nodes in that subtree change as well. You can see that the only current method to change the tree, `SyntaxNode::replace_with`, basically re-creates a new tree [here](https://docs.rs/cstree/0.4.0/src/cstree/syntax/node.rs.html#522-539) (note that this is less bad than it sounds, it does _not_ re-make underlying green nodes that are not on the path from the root to the edit).

For (1), this means that you _can_ use `replace_with` to modify the green tree, but will be required to re-build the red tree on top. I know matklad is very actively working on a better editing interface for `rowan` trees right now, where the syntax level tree has an added linked list to track what nodes are part of the tree. As far as I'm aware, this requires only one copy upfront, but then ofc you have some overhead for keeping track of the mutations. I'm not entirely up to date on the implementation, you can have a look at https://github.com/rust-analyzer/rust-analyzer/issues/6857. Notably though, they modify the tree through interior mutability (shared references), which would require synchronization for us since `cstree`'s nodes are `Send` and `Sync`.

An approach to construct less changed trees, which also relates to (2), is grouping your tree updates in some way before applying them and/or finding out which part needs to be replaced. E.g. https://github.com/rust-analyzer/rust-analyzer/blob/ac123ac9e41c14296154ba42bb432e03dffa8b24/crates/parser/src/lib.rs#L133, https://github.com/rust-analyzer/rust-analyzer/blob/152f385055510c65bd94238878be23a258f5cc19/crates/parser/src/grammar.rs#L147, https://github.com/rust-analyzer/rust-analyzer/blob/c49b5b7468a9954af86fd1724276261f396aba5d/crates/syntax/src/parsing/reparsing.rs#L124 combine to find the smallest node that covers a change, which could be extended to multiple changes close to one another. 

Apart from all of that, you can always re-use either or both of the string interner and the node cache across many trees. That actually makes a lot of sense if you always parse the same language, and even more if that language has repetitive elements like assigning fixed values, or description languages. Both of these are relatively independent of tree modifications.

I hope that clears things up for you, if you have further questions please don't hesitate to ask! I realize I wrote a bit of a novel, but I hope this issue can be useful for future reference and to other as well. 

Definitely will leave this open and try to at least write a small example that uses `replace_with` to swap in a specific new node. Actual incremental parsing may be a bit out of scope just for an example, given how much surrounding code it requires, although I wouldn't say no if someone added such an example, as the use case is of course important.

**Comment by skyne98** [comment] 2021-04-11 01:58
Thanks for such a detailed answer! In my opinion in such matters it's much better to go into detail than to write something ambiguous, so no problem. So, if I got it correctly, the problem is that if you decide to only update a part of the tree, even though the "green" tree doesn't really change (as it has no absolute positional values) some part of the "red" tree, which comes after the part we have updated (like an else block if we replaced the if's body) will have to recalculate their offsets. 

I see how it can quickly become a problem - a small modification in the very beginning of the file will require offset recalculation of the entirety of the tree. I wonder how they solved it for Roslyn? Furthermore, I might have to read some materials, or the article you provided tomorrow to get a little more insight. I might assume they just accept this fact and write additional code to handle this case? Though, it kinda feels weird, when we are talking about immutable trees, as they should not change on modification.

For now, I only see a couple of ways to solve this problem:
1. A naive approach of writing some helper functions that will copy and recreate a whole tree structure according to modifications you made. This approach seems pretty easy, but sounds incredibly costly. Also, this one will not require any changes to the library and can be done externally.
2. The second one is an idea to have two types of trees: "raw" and "baked". "Baked" ones are the completely immutable ones which record their absolute offsets from the root element. "Raw" elements are the ones who have their offset always calculated on the fly by traversing the tree to the top. Both "baked" and "raw" trees will have methods for their modification, but both will return a new "raw" subtree, which you can then "bake" for further use. Both of then, in theory, can be completely similar, persistent and immutable, the only different is that they will be making different trade-offs between performance and functionality.

What do you think?

**Comment by domenicquirl** [comment] 2021-04-11 15:10
Your understanding of the green vs. red tree is correct. When changing a node, there are two invalidations that happen. One of the green tree, which affects only the path from the edit to the root, so the green tree can (and does) re-use all other, unaffected nodes. The other of the red tree, which affects a varying range of the tree depending on the changed node's position. At the moment, `cstree` makes you create a new red tree for this second invalidation.

Wrt. how much of a problem this is, that depends somewhat on the rest of the implementation. Obviously, in an ideal world we'd have to invalidate less, but an interesting point is also that in both `rowan` and `cstree` the red trees are _lazy_. When you call `new_root`, you will only get a root node. Other nodes in the tree are created on-the-fly when you start traversing the root's children (or more generally descendants).
This means that if you've only looked at part of a syntax tree, only that part exists and can become invalid. `rowan` and `cstree` differ in what they do _after_ you've looked at some node: `cstree` remembers them and will give you the exact same node the next time you look in that spot, in order to avoid deleting and re-creating nodes all the time, while `rowan` will always re-create everything in the on-the-fly way (with some opts). But for both, in the worst case all red nodes change and have to be recomputed. AFAIK Roslyn also uses lazy nodes, and uses weak references to reduce memory (so closer to the `rowan` way where sometimes you re-create nodes, but they have garbage collection).

So this is basically all re: (1). In a way it is the point of the red/green split that you can keep most of the green tree (which contains all actual text, remember, the syntax nodes "only" hold the tree structure) and only need to invalidate and rebuild the red one (which is then way less costly than rebuilding all of the tree).

(2) is very similar to the approach currently pursued by `rowan`, just in reverse (start with the unmodifiable tree, make a copy that can be mutated). To be honest it doesn't sound to me like you would get much better performance by re-computing everything all the time than from the "mutable tree" list structure that they are investigating, because you have to keep in mind that it is not sufficient to just move back up the tree - if the other nodes in the tree do not keep positional/structural information, then the only thing you know is that the root starts at 0. You would always need to traverse all nodes _before_ the node you are interested in, recursively, to compute it's offset, which in the worst case is again the entire tree.
That said, this would be easier to implement for `cstree` than actual modification, again because `cstree` trees can be shared between threads, so all modifications are potentially concurrent (_that_ said, there is also still #5, at which point it might be possible to have this API conditionally). But I also see some API concerns with having `SyntaxNode`, `ResolvedNode`, `RawNode` and how many else this might need, that all basically do the same thing.

Overall, it maybe helps you to imagine only the green tree as the immutable data structure, and the red tree as a convenient interface on top? Because the green trees _do_ only add the changed part of the tree and re-use the rest. If I understand, the red tree changing more or less completely is the part that feels off to you.

**Comment by domenicquirl** [comment] 2021-04-11 15:11
Also, out of personal interest, how did you find `cstree`? It's not been alive for that long, and as far as I know no one posted an announcement ☺️

**Comment by skyne98** [comment] 2021-04-11 16:31
I just really appreciate the work smart people put into their well-rounded self-contained packages that solve one specific problem really well, `cstree` looked like `rowan` + some additional goodies to me 😃 Found it by just searching on [Lib.rs](https://lib.rs)!

**Comment by skyne98** [comment] 2021-04-11 17:15
> If I understand, the red tree changing more or less completely is the part that feels off to you.
Honestly speaking - yep, it just feels a little off to recreate such a big structure because of small changes, however, I also understand how potentially cheap it is.

(1)
By the way, what do you think about this small improvement idea: let's imagine that SyntaxElement's offset is not absolute anymore, but relative to its parent. Now let's imagine we have a scenario like this:
```
if (<condition>) {
    <then-body>
} else {
    <else-body>
}
```
Assuming we have changed the `then-body` and we have absolute positions we will have to invalidate and recreate the whole of `<else-body>`. If we have relative offsets, then, in my imagination, only one "horizontal slice" of elements will have to get updated, while all of their children can remain exactly the same and can be re-used. However, this might be an example of making code more complicated for barely any gains at all, if the "red" tree recreation is very cheap. Also, again, it will lead to some complications in resolution of actual source code text.

(2)
So, just to make sure my whole understanding is correct, this is how I see the structure at the moment:
* "Green" tree is not really a tree and is exactly what makes the whole system persistent, as it relies on storing and getting them based on the hash of their actual position-independent data
* "Red" tree elements are just, technically speaking, wrappers around "green" ones adding some lightweight additional information (exactly an offset in the source text). Also, as far as I understood it, because "red" nodes are just wrappers, `rowan` treats them as values and always creates a new one for you, but `cstree` tries to reuse them to save some memory and performance.
* By extending the architecture, ASTs are just extremely lightweight wrappers around the "red" tree elements, which are created on the fly from their `SyntaxElement` counterparts. As an example, a body of some function declaration AST node will just be a reference to a `SyntaxNode`, which on calling `get_body` will be turned into another wrapping AST node.
* If I want to provide an API for easily replacing parts of the tree (something like `fn_declaration.with_idenfifier(new_identifier)`), then those methods will have to return completely new "red" trees on each call with their offsets calculated from zero. In this case, I wonder what those methods will have to return - the root of the new tree or the updated copy of the element it was called on with an ability to traverse it back if you need to? I might have to look into packages which use `rowan` for some examples or maybe you have some ideas about it?

**Comment by domenicquirl** [comment] 2021-04-11 18:55
1. My question would be where the relative offsets stop. If I hold the relative offset to my parent, then my parent is also a node and will hold the relative offset to _it's_ parent. And then you're back to only knowing the root's offset is 0 and having to traverse the whole tree to compute any other offset. That's definitely not a clear win to me, as it is very possible traversing an unchanged tree happens more often than edits (in particular, in more analysis-heavy use cases like in a compiler or linter). It may be interesting to see the difference in a scenario like a language server, where you mostly run analyses when a file changes. But even then there can be stretches where users mostly navigate around with "go to definition" or "find references", the question would be how much you rely on offsets in these cases. It's used to give you text ranges though, not just the resolution to source text, which are important to report anything back to a client (where something should be highlighted, or an error displayed, etc.)
2. Green trees make up the immutable data structure and are technically a DAG (so not a tree). They are persistent, but there is also a distinction about whether red nodes are persistent across different tree traversals or not, which is a difference between `cstree` and `rowan`. Persisting them saves memory _allocations_, but not total memory, as you always keep the entire tree around. Note that the red nodes also put on the actual tree structure that differentiates the green tree DAG.
Correct on the AST layer. That is obviously custom since it depends on the kinds of nodes that you have as a user, but you can make it literally
```rust
pub struct Function<D: 'static = ()> {
    pub(crate) syntax: SyntaxNode<D>,
}
```
or, alternatively, use a reference (or/and a `ResolvedNode`, there are some options).

Regarding your renaming API, `SyntaxNode::replace_with` will give you a new _root_ `GreenNode`. So if you want a new red tree you `new_root[_with_resolver]` that. I don't know whether people then usually walk that to find the function declaration again, functionally you can walk in either direction. Depending on your use case you'll have to see what changes make sense to do on the tree directly, and what changes make sense to do on the source.

**Closed** 2021-04-26 07:20 UTC
